# rules https://docs.astral.sh/ruff/rules
line-length = 120
indent-width = 4


extend-exclude = ["practice", "tests"]


[lint]
unfixable = ["ALL"]

ignore = [
    "PERF401", # use list comprehension instead of generator expression
    "PERF403", # use dict comprehension instead of generator expression
    "PLR1711", # useless return.
    "PLR1712", # swap-with-temporary-variable. This is a refactor rule that is not relevant for students.
    "PLR1714", # repeated-equality-comparison
    "PLR1716", # boolean-chained-comparison
    "PLR1722", # use sys.exit() instead of exit()
    "PLR1730", # if-stmt-min-max. This is a refactor rule that is not relevant for students.
    "PLR2004", # magic-value-comparison. This is a refactor rule that is not relevant for students.
    "PLR5501", # collapsible-else-if. This is a refactor rule that is not relevant for students.
    "N806",    # non-lowercase-variable-in-function. Allow uppercase variable names in functions
    "ISC002",  # Checks for implicitly concatenated strings that span multiple lines. Why not let students do it?
    "ISC003",  # Checks for string literals that are explicitly concatenated (using the + operator).Why not let students do it?
    "E302",    # forces 2 blank lines between functions
    "E303",    # forces 2 blank lines between functions
    "E502",    # Redundant backslash
    "E711",    # none-comparison
    "E712",    # true-false-comparison if foo instead och if foo == true
    "W291",    # trailing whitespaces
    "W293",    # Blank line contains whitespace
    "W505",    # doc line too long
    "PLC1802", # len({expression}) used as condition without comparison
    "PLC1901", # {existing} can be simplified to {replacement} as an empty string is falsy
    "PLW0603", # global-statement. Allow global statements in functions, as it is a common pattern for students to use global variables in functions.
    "UP009",   # utf-8 encoding declaration
    "UP012",   # unnecessary-encode-utf8
    "UP015",   # redundant-open-modes
    "UP030",   # format-literals
    "UP032",   # f-strings-over-format
]


# If you want to use for OO code, there are more rules to add ex. https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi
#  utkommenterade rader kräver att preview mode är aktiverat
select = [
    "A",       # prevent using keywords that clobber python builtins
    "B",       # bugbear: security warnings
    "E",       # pycodestyle, error
    "W",       # pycodestyle, warning
    "F",       # pyflakes
    "N",       # pep8-naming
    "PLE",     # Errors
    "PLR",     # Refactor
    "PLW",     # Warning
    "ISC",     # implicit string concatenation
    "ARG",     # flake8-unused-arguments 
    "PERF",    # flake8-unused-arguments 
    "C90",     # looks for complex functions
    "UP",      # alert you when better syntax is available in your python version
    "TID251",  # disallow importing specific modules
    "T10",     # looks for breakpoints in code. Should not be in production code
    "S102",    # use of `exec`
    "BLE001",  # use of base exception classes
    "EXE005",  # shebang is not first line
    "Q003",    # avoid escaping quotes
    "Q004",    # unnecessary escaped quotes
    "RET505",  # superfluous-else-return
    "RET506",  # superfluous-else-raise
    "RET507",  # superfluous-else-continue
    "RET508",  # superfluous-else-break
    "SLF001",  # Private member accessed
    "SIM114",  # Combine if branches using logical or operator
    "SIM115",  # Use a context manager for opening files
    "SIM210",  # Remove unnecessary True if ... else False
    "SIM910",  # Include default value in dict.get() call
    "SIM911",  # Use dict.items() instead of zip()
    "PLC0206", # Extracting value from dictionary without calling .items()
    "PLC2401", # {kind} name {name} contains a non-ASCII character
    "PLC2403", # Module alias {name} contains a non-ASCII character
    # "PLC2701", # Private name import {name} from external module {module}
    # "PLC2801", # Unnecessary dunder call to {method}. {replacement}.
    "PLC3002", # Lambda expression called directly. Execute the expression inline instead.
    "TRY203",  # Remove exception handler; error is immediately re-raised
    "TRY301",  # Abstract raise to an inner function
    "RUF001",  # Ambiguous unicode character string
    "RUF059", # Checks for unused unpacked variabel
]


# Add modules that should not be imported/used!
[lint.flake8-tidy-imports.banned-api]
"re".msg = "Regex is not part of this course. Everything you can do with regex, you can do using things taught in the course."
"regex".msg = "Regex is not part of this course. Everything you can do with regex, you can do using things taught in the course."

# Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
"**/main.py" = [
    "C901",
    "PLR0912",
    "PLR0915",
] #  too-complex, ignore too-many-branches, to many statements

[lint.pylint]
max-branches = 10
max-args = 7


[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
ignore-overlong-task-comments = true

[format]
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
quote-style = "double"
