#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import os
import re
import unittest
from io import StringIO
from unittest import TextTestRunner
from unittest.mock import patch

from tester import (
    ExamTestCase,
    ExamTestResult,
    import_module,
    setup_and_get_repo_path,
    tags,
)

FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = setup_and_get_repo_path(FILE_DIR)

# Path to file and basename of the file to import
main = import_module(REPO_PATH, "main")
marvin2 = import_module(REPO_PATH, "marvin2")


class Test2Marvin2NewMenus(ExamTestCase):
    """
    Each assignment has 1 testcase with multiple asserts.
    The different asserts https://docs.python.org/3.6/library/unittest.html#test-cases
    """

    def check_print_contain(self, inp, correct, func):
        """
        One function for testing print input functions.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                func()
                str_data = fake_out.getvalue()
                for val in correct:
                    self.assertIn(val, str_data)

    @tags("5", "marvin2")
    def test_create_ssn_func(self):
        """
        Testar att anropa menyval 5 via main funktionen i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att ett giltigt personnummer har rätt struktur:
        {correct}
        Det har inte strukturen, ÅÅMMDD-NNNN:
        {student}
        """
        self.norepr = True
        birthdate = "030123"
        self._multi_arguments = ["5", birthdate, "", "q"]

        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()

        pattern = r"[^\d](030123-\d{4})[^\d]"
        self.fail_msg.student_answer = str_data
        self.fail_msg.correct_answer = repr(f"{birthdate}-NNNN")
        if re.search(pattern, str_data) is None:
            raise AssertionError
        ssn = re.search(pattern, str_data)[1]

        self._multi_arguments = ["4", ssn, "", "q"]
        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()
            self.assertIn(
                "Valid",
                str_data,
                msg=[
                    "Använder funktionen 'validate_ssn()' för att validera det genererade personnummret:",
                    "Personnummret var inte giltigt:",
                ],
            )

    @tags("6", "marvin2")
    def test_roll_dice_menu(self):
        """
        Testar att anropa menyval 6 via main funktionen i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att utskriften innehåller uttrycket följt av ett kolon och ett heltal i rätt intervall:
        {correct}
        Fick följande:
        {student}
        """
        expr = "3d6+5"
        self._multi_arguments = ["6", expr, "", "q"]

        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()

        pattern = r"3d6\+5: (\-?\d+)"
        self.fail_msg.student_answer = str_data
        self.fail_msg.correct_answer = repr(f"{expr}: <8-23>")

        match = re.search(pattern, str_data)
        if match is None:
            raise AssertionError
        result = int(match[1])
        self.assertGreaterEqual(result, 8)
        self.assertLessEqual(result, 23)


if __name__ == "__main__":
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
