#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import os
import unittest
from io import StringIO
from unittest import TextTestRunner
from unittest.mock import patch

from tester import (
    ExamTestCase,
    ExamTestResult,
    import_module,
    setup_and_get_repo_path,
    tags,
)

FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = setup_and_get_repo_path(FILE_DIR)


class Test2Marvin1(ExamTestCase):
    """
    Each assignment has 1 testcase with multiple asserts.
    The different asserts https://docs.python.org/3.6/library/unittest.html#test-cases
    """

    link_to_assignment = "https://bth-python.github.io/laromaterial/uppgift/marvin1/"

    def check_print_contain(self, inp, correct):
        """
        One function for testing print input functions.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                import_module(REPO_PATH, "marvin")
                str_data = fake_out.getvalue()
                for val in correct:
                    self.assertIn(val, str_data)

    def check_print_not_contain(
        self,
        inp,
        correct,
        msg=[
            "Förväntar att följande inte finns med i utskrifter:",
            "Fick med följande:",
        ],
    ):
        """
        One function for testing print input functions.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                import_module(REPO_PATH, "marvin")
                str_data = fake_out.getvalue()
                for val in correct:
                    self.assertNotIn(val, str_data, msg)

    @tags("1")
    def test_a_greeting_includes_name(self):
        """
        Testar menyval 1 och q
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["1", "Benny", "", "q"]
        self.check_print_contain(self._multi_arguments, ["Benny"])

    @tags("2")
    def test_b_temperature_high(self):
        """
        Testar att anropa menyval 2 med ett positivt värde.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["2", "135.205", "", "q"]
        self.check_print_contain(self._multi_arguments, ["275.37"])

    @tags("2")
    def test_b_temperature_low(self):
        """
        Testar att anropa menyval 2 med ett negativt värde.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["2", "-252.454", "", "q"]
        self.check_print_contain(self._multi_arguments, ["-422.42"])

    @tags("3")
    def test_l_compare_small_larger_two(self):
        """
        Testar menyval 3
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "2", "11", "4"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_contain(self._multi_arguments, ["smaller!", "larger!"])

    @tags("3")
    def test_m_compare_small_larger(self):
        """
        Testar menyval 3 och att det inte printas ut "same!" när det inte är samma nummer
        Använder följande som input:
        {arguments}
        Förväntar att följande inte finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "2", "11", "4"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_not_contain(self._multi_arguments, ["same!"])

    @tags("3")
    def test_n_compare_same_smaller(self):
        """
        Testar menyval 3 där två nummer är lika.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "11", "10", "10"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_contain(self._multi_arguments, ["same!", "smaller!"])

    @tags("3")
    def test_o_compare_same_smaller_two(self):
        """
        Testar menyval 3, där två nummer är lika och att det inte printas ut "larger!" när det inte är större nummer.
        Använder följande som input:
        {arguments}
        Förväntar att följande inte finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "11", "10", "10"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]
        self.check_print_not_contain(self._multi_arguments, ["larger!"])

    @tags("3")
    def test_p_compare_same_larger(self):
        """
        Testar menyval 3, där två nummer är lika och att det inte printas ut "smaller!" när det inte är mindre nummer.
        Använder följande som input:
        {arguments}
        Förväntar att följande inte finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "12", "12", "12", "14"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]
        self.check_print_not_contain(self._multi_arguments, ["smaller!"])

    @tags("3")
    def test_q_compare_same_larger_two(self):
        """
        Testar menyval 3, där två nummer är lika och att det printas ut "same!" och "larger!" när det är lika och större nummer.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "12", "12", "12", "14"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_contain(self._multi_arguments, ["same!", "larger!"])

    @tags("3")
    def test_q_compare_not_a_number(self):
        """
        Testar menyval 3 där användaren inte bara skriver in siffror
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "hej", "12", "test", "2"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_contain(
            self._multi_arguments,
            ["not a number!", "larger!", "not a number!", "smaller!"],
        )

    @tags("3")
    def test_q_compare_float_negative(self):
        """
        Testar menyval 3, där negativt flyttal används.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        numbers = ["11", "2", "11", "-3.14"]

        self.norepr = True
        self._multi_arguments = ["3", *numbers, "done", "", "q"]

        self.check_print_contain(self._multi_arguments, ["smaller!", "larger!"])

    @tags("4")
    def test_r_valid_ssn(self):
        """
        Testar menyval 4 med giltigt personnummer.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """

        self.norepr = True
        self._multi_arguments = ["4", "811218-9876", "", "q"]

        self.check_print_contain(self._multi_arguments, ["Valid"])

    @tags("4")
    def test_r_not_valid_ssn(self):
        """
        Testar menyval 4 med icke-giltigt personnummer.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """

        self.norepr = True
        self._multi_arguments = ["4", "231218-9874", "", "q"]

        self.check_print_contain(self._multi_arguments, ["Not valid"])

    @tags("4")
    def test_r_valid_ssn_format(self):
        """
        Testar menyval 4 med giltigt personnummer där bindestreck saknas.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """

        self.norepr = True
        self._multi_arguments = ["4", "8181818181", "", "q"]

        self.check_print_contain(self._multi_arguments, ["Valid"])

    @tags("4")
    def test_r_not_valid_ssn_extra(self):
        """
        Testar menyval 4 med personnummer det är en siffra för mycket på slutet.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """

        self.norepr = True
        self._multi_arguments = ["4", "818181-81812", "", "q"]

        self.check_print_contain(self._multi_arguments, ["Not valid"])

    @tags("4")
    def test_r_not_valid_ssn_extra2(self):
        """
        Testar menyval 4 med personnummer det är en siffra för mycket på slutet men inget bindestreck mitt i.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """

        self.norepr = True
        self._multi_arguments = ["4", "81818181812", "", "q"]

        self.check_print_contain(self._multi_arguments, ["Not valid"])


if __name__ == "__main__":
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
