#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import os
import unittest
from io import StringIO
from unittest import TextTestRunner
from unittest.mock import patch

from tester import (ExamTestCase, ExamTestResult, import_module,
                    setup_and_get_repo_path, tags)

FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = setup_and_get_repo_path(FILE_DIR)


class Test1ConvertStructure(ExamTestCase):

    def get_output_from_program(self, inp):
        """
        One function for testing print input functions
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                import_module(REPO_PATH, "convert")
                return fake_out.getvalue()

    @tags("extra")
    def test_a_value_not_int_catch_with_ValueError(self):
        """
        Testar skicka in sträng värde som input. Kollar att felhantering genom att fånga ValueError.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._argument = "inte int"
        try:
            output_from_program = self.get_output_from_program([self._argument])
            self.assertIn("ValueError", output_from_program)
        except SystemExit:
            pass



if __name__ == "__main__":
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
