#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import os
import unittest
from io import StringIO
from unittest import TextTestRunner
from unittest.mock import patch

from tester import (
    ExamTestCase,
    ExamTestResult,
    import_module,
    setup_and_get_repo_path,
    tags,
)

FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = setup_and_get_repo_path(FILE_DIR)

# Path to file and basename of the file to import
main = import_module(REPO_PATH, "main")


class Test2LeaderboardMain(ExamTestCase):
    """
    Each assignment has 1 testcase with multiple asserts.
    The different asserts https://docs.python.org/3.6/library/unittest.html#test-cases
    """

    link_to_assignment = (
        "https://bth-python.github.io/laromaterial/uppgift/leaderboard/"
    )

    def check_print_contain(self, inp, correct=None):
        """
        One function for testing print input functions.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()
                if correct:
                    for val in correct:
                        self.assertIn(val, str_data)
                return str_data

    def check_print_not_contain(self, inp, correct):
        """
        One function for testing that values are absent from output.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                for val in correct:
                    str_data = fake_out.getvalue()
                    self.assertNotIn(
                        val,
                        str_data,
                        [
                            "Förväntar att följande inte finns med i utskrifter:",
                            "Fick med följande:",
                        ],
                    )

    @tags("1")
    def test_stats(self):
        """
        Testar att anropa menyval 1.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["1", "", "q"]

        correct = ["4", "5800", "1450", "Charlie", "2300", "Bob", "800"]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("1", "empty")
    def test_stats_empty(self):
        """
        Testar att anropa menyval 1 när alla spelare har tagits bort.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = [
            "4",
            "Alice",
            "",
            "4",
            "Bob",
            "",
            "4",
            "Charlie",
            "",
            "4",
            "Dana",
            "",
            "1",
            "",
            "q",
        ]

        correct = ["Inga spelare i highscore-listan."]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("2")
    def test_players_by_level(self):
        """
        Testar att anropa menyval 2 med en nivå som finns och att resultatet är sorterat högt till lågt.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift i ordningen högt till lågt:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        # Add Erik (950, Nybörjare) then search Nybörjare — should show Bob (800) after Erik (950)
        self._multi_arguments = [
            "3",
            "Erik",
            "950",
            "Nybörjare",
            "",
            "2",
            "Nybörjare",
            "",
            "q",
        ]

        correct = ["Erik (950 poäng)", "Bob (800 poäng)", "Antal: 2"]
        data = self.check_print_contain(self._multi_arguments, correct)
        self.assertOrder(correct, data)

    @tags("2", "missing")
    def test_players_by_level_not_found(self):
        """
        Testar att anropa menyval 2 med en nivå som inte finns.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["2", "Mästare", "", "q"]

        correct = ['Inga spelare på nivå "Mästare" hittades.']
        self.check_print_contain(self._multi_arguments, correct)

    @tags("3", "add")
    def test_add_new_player(self):
        """
        Testar att lägga till en ny spelare via menyval 3.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["3", "Erik", "950", "Nybörjare", "", "q"]

        correct = ["Erik har lagts till."]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("3", "update")
    def test_update_existing_player(self):
        """
        Testar att uppdatera en befintlig spelare via menyval 3.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["3", "Alice", "2000", "Elit", "", "q"]

        correct = ["Data uppdaterad för Alice."]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("3", "1")
    def test_add_then_stats(self):
        """
        Testar att lägga till en ny spelare via menyval 3 och sedan kolla statistik via menyval 1.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["3", "Erik", "950", "Nybörjare", "", "1", "", "q"]

        correct = ["Erik har lagts till.", "5", "6750"]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("4")
    def test_remove_player(self):
        """
        Testar att ta bort en spelare via menyval 4.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["4", "Bob", "", "q"]

        correct = ["Bob har tagits bort."]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("4", "missing")
    def test_remove_player_not_found(self):
        """
        Testar att ta bort en spelare som inte finns via menyval 4.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["4", "Zlatan", "", "q"]

        correct = ["Spelaren Zlatan hittades inte."]
        self.check_print_contain(self._multi_arguments, correct)

    @tags("4", "2")
    def test_remove_then_level(self):
        """
        Testar att ta bort en spelare via menyval 4 och sedan söka på deras nivå via menyval 2.
        Använder följande som input:
        {arguments}
        Förväntar att spelaren inte längre syns vid sökning på nivå:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["4", "Bob", "", "2", "Nybörjare", "", "q"]

        correct = ["Bob har tagits bort.", 'Inga spelare på nivå "Nybörjare" hittades.']
        self.check_print_contain(self._multi_arguments, correct)


if __name__ == "__main__":
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
